	<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>
	<meta charset="utf-8">
	<link type="image/x-icon" href="static/images/favicon.ico" rel="shortcut icon">	
	<!-- jQuery -->
	<script type="text/javascript" src="static/bower_components/jquery/dist/jquery.min.js" ></script>
	<script type="text/javascript" src="static/bower_components/jquery/dist/jquery-form.js" ></script>
	
	<!-- Bootstrap 核心 CSS -->
	<link rel="stylesheet" href="static/bower_components/bootstrap/dist/css/bootstrap.min.css" >
	<link rel="stylesheet" href="static/bower_components/bootstrap/dist/css/bootstrap-theme.css" ></link>
	<script type="text/javascript" src="static/bower_components/bootstrap/dist/js/bootstrap.min.js" ></script>
	
	<!-- 表单验证css -->
	<link rel="stylesheet" href="static/bower_components/validator/dist/css/bootstrapValidator.min.css" ></link>
	<script type="text/javascript" src="static/bower_components/validator/dist/js/bootstrapValidator.min.js" ></script>
	
	<!-- 滚动菜单核心文件  -->
	<link rel="stylesheet"  href="static/bower_components/metisMenu/dist/metisMenu.min.css" >
	<script type="text/javascript" src="static/bower_components/metisMenu/dist/metisMenu.min.js" ></script>
	
	<!-- DataTables CSS -->
	<link rel="stylesheet" href="static/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.css" >
	<!-- DataTables Responsive CSS -->
	<link rel="stylesheet" href="static/bower_components/datatables-responsive/css/dataTables.responsive.css" >
	<!-- DataTables JavaScript -->
	<script src="static/bower_components/datatables/media/js/jquery.dataTables.min.js" ></script>
	<script src="static/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js" ></script>
	
	<!-- 	公共js文件，加载获取URL参数的方法 -->
	<script type="text/javascript" src="static/js/public.js" ></script>
	
	<!-- 定制样式 CSS -->
	<link rel="stylesheet" href="static/dist/css/sb-admin-2.css" >
	<script type="text/javascript" src="static/dist/js/sb-admin-2.js" ></script>

	<!-- 图标样式文件  -->
	<link rel="stylesheet" href="static/bower_components/font-awesome/css/font-awesome.min.css" >
	
	<script type="text/javascript" src="static/bower_components/layer/layer.js" ></script>
	